favicon: /favicon.ico


# Nav Menus
menu:
    现在: /
    曾经: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/derekhe']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['GitHub', 'http://github.com/derekhe']
    - ['简书', 'http://www.jianshu.com/u/b1e713e56ea6']
    - ['LinkedIn', 'https://www.linkedin.com/in/sicong-he-56a95437/']

# About
about_info:
    name: "he.sicong"
    bio: ""
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun

# Analytics
tencent_analytics: 
 
# Copyright Infomation
startyear: 2008
