favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    Archives: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/derekhe']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - []

# About
about_info:
    name: "he.sicong"
    bio: ""
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun

# Analytics
tencent_analytics: 
 
# Copyright Infomation
startyear: 2017
